# MedCross 后端配置文件

server:
  port: "8080"

# 数据库配置
database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  user: "medcross"
  password: "your_secure_password"  # 生产环境中请使用强密码
  dbname: "medcross"
  sslmode: "disable"  # 生产环境建议使用require
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# 以太坊配置
ethereum:
  rpc_url: "http://localhost:8545"  # 以太坊私链RPC地址
  contract_address: "0x0000000000000000000000000000000000000000"  # 部署后的合约地址
  private_key: ""  # 用于签名交易的私钥

# Fabric配置
fabric:
  config_path: "./fabric-config"  # Fabric连接配置文件路径
  channel_id: "mychannel"  # 通道ID
  chaincode_name: "medicaldata"  # 链码名称
  user_name: "Admin"  # 用户名
  org_name: "Org1"  # 组织名称

# JWT配置
jwt:
  secret: "medcross_secret_key"  # JWT签名密钥
  expires_in: 86400  # 过期时间（秒）